Refactor VPC loadbalancer example
selectel/terraform-examples pull request #29
Opened 2021-12-06 23:52 UTC by Koodt

Add new load balancer examples
Fix external network datasource
Fix readme
Fix gitignore

2021-12-09 22:41 UTC, kolsean requested changes

2021-12-09 22:41 UTC, kolsean commented on examples/vpc/several_servers_and_loadbalancers_without_project/README.md
> +# Пример создания двух серверов и двух балансировщиков с правилами TCP, UDP и HTTPS с SSL сертификатом с использрванием уже существующих пользователя и проекта
с использованием

2021-12-09 22:41 UTC, kolsean commented on examples/vpc/several_servers_and_loadbalancers_with_project/main.tf
> +# Создание балансировщика базового типа с резервированием, HTTPS правилом и SSL сертификатом
Не обязательно, но было бы здорово все представленные примеры оформлять в дальнейшем в едином стиле.
В текущем и других файлах в комментариях точка либо присутствует, либо ее нет. Вроде бы мелочь, но в глаза бросается.

2021-12-09 22:41 UTC, kolsean commented on modules/vpc/os_lb_env/README.md
> +- сетевая инфарструктура
инфраструктура

2021-12-09 22:41 UTC, kolsean commented on modules/vpc/lb_sngl/README.md
> +  * `lb_public_subnet_id` - UUID сети, в которй будет создан балансировщик.
в которой

2021-12-10 06:08 UTC, Koodt commented on examples/vpc/several_servers_and_loadbalancers_with_project/README.md
> +  По умолчанию, если оставить поле пустым, будет создан балансировщик с резевированием - два инстанса на балансировщик.
Исправлено

2021-12-10 06:09 UTC, Koodt commented on examples/vpc/several_servers_and_loadbalancers_with_project/README.md
> +  * `active_lb_floating` - Публичный IP адрес балансировщика базового типа резервированием и SSL сертификатом.
Исправлено

2021-12-10 06:09 UTC, Koodt commented on examples/vpc/several_servers_and_loadbalancers_without_project/README.md
> +# Пример создания двух серверов и двух балансировщиков с правилами TCP, UDP и HTTPS с SSL сертификатом с использрванием уже существующих пользователя и проекта
Исправлено

2021-12-10 06:09 UTC, Koodt commented on examples/vpc/several_servers_and_loadbalancers_with_project/main.tf
> +# Создание балансировщика базового типа с резервированием, HTTPS правилом и SSL сертификатом
Исправлено. Убрал везде.

2021-12-10 06:09 UTC, Koodt commented on modules/vpc/lb_sngl/README.md
> +  * `lb_public_subnet_id` - UUID сети, в которй будет создан балансировщик.
Исправлено

2021-12-10 06:09 UTC, Koodt commented on modules/vpc/os_lb_env/README.md
> +- сетевая инфарструктура
Исправлено

2021-12-10 08:04 UTC, kolsean approved these changes
👍

2021-12-10 08:07 UTC, merged