Update main.tf
selectel/terraform-examples pull request #46
Opened 2023-06-24 09:52 UTC by isaevdo

Added data about Kubernetes version, that aviable to use in cluster

2023-06-26 07:35 UTC, kolsean requested changes

2023-06-26 07:35 UTC, kolsean commented on examples/mks/cluster_one_nodegroup_with_net_infra/main.tf
> +# Take information about aviable kubernetes version
typo - available

2023-06-27 09:44 UTC, kolsean requested changes
Looks good. It will be great if we also make the same update for the following example file: `examples/mks/cluster_one_nodegroup/main.tf`

2023-06-27 18:24 UTC, TawR1024 commented on examples/mks/cluster_one_nodegroup_with_net_infra/main.tf
> +# Take information about available kubernetes version
it seems that should be `versions`

2023-06-29 10:25 UTC, kolsean approved these changes

2023-06-29 11:05 UTC, merged